server:
    port: 8080

logging:
  level:
    org.springframework.security: DEBUG


# Wire Spring to use the Postgres settings
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5051/ecomdb
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

# If you need an in-memory DB for local dev, uncomment the section below and activate a 'dev' profile.
#spring:
#  datasource:
#    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driver-class-name: org.h2.Driver
#    username: sa
#    password: ""
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: none
#  flyway:
#    enabled: true
#    locations: classpath:db/migration
#    baseline-on-migrate: true

# JWT configuration
jwt:
  secret-key: OUtdpnoo3axaFX3xFUk7VMynMrGMjgTf3IWOCubmXdL+h8l7ZrayQOXj2Nf9iABAvHBm+oq9Ci084U/INT6lWg==
  expiration-minutes: 60
  refresh-expiration: 86400
